Name = 'tochukwu henry'
print(Name[:])
print(Name[:7])
print(Name[:9])
print(Name[-14])
print("xap" in Name)
print(Name[:2])
print(Name[::-2])
print(Name[:-1])
print(Name[:-2])
print(Name[::-1])
print(Name[::-2])
print(Name.split(' '))
print(Name.split(','))
print(Name.find('o'))
print(Name.count('o'))
print(Name.find('u'))
print(Name.count('u'))
print(Name.count('tochukwu henry'))
